// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates smart reminders for users based on their profiles,
 *   routines, essential items, and the current state of tracked items.
 *
 * - generateReminders - A function that handles the reminder generation process.
 * - GenerateRemindersInput - The input type for the generateReminders function.
 * - GenerateRemindersOutput - The return type for the generateReminders function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import type { Profile, Item } from '@/lib/data';

const ProfileSchema = z.object({
  id: z.string(),
  name: z.string(),
  role: z.string(),
  avatar: z.string(),
  routine: z.string(),
  essentials: z.array(z.string()),
});

const ItemSchema = z.object({
  id: z.string(),
  name: z.string(),
  owner: z.string(),
  location: z.string(),
  status: z.enum(['In Place', 'Misplaced']),
  hasTag: z.boolean(),
});

export const GenerateRemindersInputSchema = z.object({
  profiles: z.array(ProfileSchema).describe('An array of user profiles.'),
  items: z.array(ItemSchema).describe('An array of all tracked items.'),
  currentTime: z.string().describe('The current time in ISO format.'),
});
export type GenerateRemindersInput = z.infer<typeof GenerateRemindersInputSchema>;

export const ReminderSchema = z.object({
    profileName: z.string().describe("The name of the profile the reminder is for."),
    title: z.string().describe("A short, catchy title for the reminder."),
    suggestion: z.string().describe("The detailed reminder or suggestion."),
});
export type Reminder = z.infer<typeof ReminderSchema>;

export const GenerateRemindersOutputSchema = z.object({
  reminders: z.array(ReminderSchema),
});
export type GenerateRemindersOutput = z.infer<
  typeof GenerateRemindersOutputSchema
>;

export async function generateReminders(
  input: GenerateRemindersInput
): Promise<GenerateRemindersOutput> {
  return generateRemindersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRemindersPrompt',
  input: { schema: GenerateRemindersInputSchema },
  output: { schema: GenerateRemindersOutputSchema },
  prompt: `You are an AI assistant in a household management app called HomeKeep. Your task is to generate helpful, proactive reminders for users based on their profiles, routines, and the status of their items.

Current Time: {{currentTime}}

Consider the following profiles:
{{#each profiles}}
- **{{name}} ({{role}}):**
  - Routine: {{routine}}
  - Essential Items: {{#join essentials ", "}}{{/join}}
{{/each}}

Here is the current status of all tracked items:
{{#each items}}
- **{{name}} (Owner: {{owner}}):** Status: {{status}}, Last Known Location: {{location}}
{{/each}}

Generate a list of 2-4 reminders. A good reminder is timely, relevant, and actionable.

Examples of good reminders:
- If it's morning and a user is about to leave for work, remind them to check for their essential items, especially if any are marked 'Misplaced'.
- If a child has school soon, remind the parent to check if their school bag and lunch box are ready.
- If an item is marked 'Misplaced' and belongs to someone with an upcoming routine that needs it, create a reminder to look for it.

Generate the response in JSON format according to the GenerateRemindersOutputSchema.
`,
});

const generateRemindersFlow = ai.defineFlow(
  {
    name: 'generateRemindersFlow',
    inputSchema: GenerateRemindersInputSchema,
    outputSchema: GenerateRemindersOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
