// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Generates smart reminders for users based on their profiles,
 *   routines, essential items, and the current state of tracked items.
 *
 * - generateReminders - A function that handles the reminder generation process.
 */

import { ai } from '@/ai/genkit';
import {
  GenerateRemindersInputSchema,
  GenerateRemindersOutputSchema,
  type GenerateRemindersInput,
  type GenerateRemindersOutput,
} from './schemas';

export { type GenerateRemindersInput, type GenerateRemindersOutput, type Reminder } from './schemas';

export async function generateReminders(
  input: GenerateRemindersInput
): Promise<GenerateRemindersOutput> {
  return generateRemindersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateRemindersPrompt',
  input: { schema: GenerateRemindersInputSchema },
  output: { schema: GenerateRemindersOutputSchema },
  prompt: `You are an AI assistant in a household management app called HomeKeep. Your task is to generate helpful, proactive reminders for users based on their profiles, routines, and the status of their items.

Current Time: {{currentTime}}

Consider the following profiles:
{{#each profiles}}
- **{{name}} ({{role}}):**
  - Routine: {{routine}}
  - Essential Items: {{#join essentials ", "}}{{/join}}
{{/each}}

Here is the current status of all tracked items:
{{#each items}}
- **{{name}} (Owner: {{owner}}):** Status: {{status}}, Last Known Location: {{location}}
{{/each}}

Generate a list of 2-4 reminders. A good reminder is timely, relevant, and actionable.

Examples of good reminders:
- If it's morning and a user is about to leave for work, remind them to check for their essential items, especially if any are marked 'Misplaced'.
- If a child has school soon, remind the parent to check if their school bag and lunch box are ready.
- If an item is marked 'Misplaced' and belongs to someone with an upcoming routine that needs it, create a reminder to look for it.

Generate the response in JSON format according to the GenerateRemindersOutputSchema.
`,
});

const generateRemindersFlow = ai.defineFlow(
  {
    name: 'generateRemindersFlow',
    inputSchema: GenerateRemindersInputSchema,
    outputSchema: GenerateRemindersOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    return output!;
  }
);
